//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //资源：
    'Berry': '浆果',
    'Brushwood': '灌木',
    'Mushroom': '蘑菇',
    'clothes': '衣服',
    'Forest': '森林',
    'FOOD': '食物',
    'Stone': '石头',
    'Log': '木头',
    'Wheat': '小麦',
    'Fish': '鱼',
    'Meat': '肉',
    'Fur': '毛皮',
    'Cotton': '棉花',
    'Copper': '铜',
    'Coins': '钱币',
    'Barley': '大麦',
    'Cooked meat': '烤肉',
    'Cooked Meat': '烤肉',
    'Vegetable soup': '蔬菜汤',
    'Light Armor': '轻甲',
    'Sword': '剑',
    'Tin': '锡',
    'Iron': '铁',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //建筑
    'Hut': '棚屋',
    'Warehouse': '仓库',
    'Loggers hut': '伐木工小屋',
    'Workshop': '工作台',
    'Hut heating': '棚屋加热',
    'Bakery': '面包店',
    'Brewery': '啤酒厂',
    'Cotton mill': '纺织厂',
    'Sawmill': '锯木厂',
    'Mint': '造币厂',
    'Fishers hut': '渔民小屋',
    'House': '房屋',
    'Stonemason': '石匠',
    'Tailor': '裁缝',
    'Tannery': '制革厂',
    'Tavern': '酒馆',
    'Windmill': '风车',
    'Winery': '酿酒厂',
    'Market': '市场',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //科技
    'Bow': '弓箭',
    'Calendar': '日历',
    'Fire': '火',
    'Fishing': '渔业',
    'Foresight': '预卜',
    'Mortar': '砂浆',
    'Stone axe': '石斧',
    'Stone Axe': '石斧',
    'Stone hammer': '石锤',
    'Stone pickaxe': '石镐',
    'Stone shovel': '石铲',
    'Stone spear': '石矛',
    'Stone Hammer': '石锤',
    'Stone Shovel': '石铲',
    'Stone Spear': '石矛',
    'Can hitting with stone be easier?': '用石头击打会更容易吗？',
    'Could there be something edible in the water?': '水中有可食用的东西吗？',
    'Could we kill without coming closer?': '我们可以杀死而不用靠近吗？',
    'If only we knew what we don\'t know': '只要我们知道我们不知道的事情',
    'Is there some pattern to seasons?': '季节有一些模式吗？',
    'It should be better to get your stone dirty and not your hands?': '你的石头应该更好而不是你的手？',
    'It\'s probably more effective to hit trees with sharp stone?': '用锋利的石头打树可能更有效吗？',
    'We would have better chance of survival if we keep enemy at distance?': '如果我们让敌人保持距离，我们将有更好的生存机会？',
    'Would it be useful if we could start fire on demand?': '如果我们可以按需开火，它会有用吗？',
    'Would it be useful to ground things up?': '将事情搞清楚会有用吗？',
    'Would stone win against stone?': '石头会打赢石头吗？',
    'Are you sure you want to unlock researching Stone pickaxe?': '你确定要解锁研究石镐吗？',
    'Are you sure you want to unlock researching Stone axe?': '你确定要解锁研究石斧吗？',
    'Are you sure you want to unlock researching Foresight?': '您确定要解锁研究预卜吗？',
    'Are you sure you want to unlock researching Calendar?': '您确定要解锁研究日历吗？',
    'Are you sure you want to unlock researching Stone spear?': '您确定要解锁研究石矛吗？',
    'Are you sure you want to unlock researching Stone shovel?': '您确定要解锁研究石铲吗？',
    'Are you sure you want to unlock researching Stone hammer?': '您确定要解锁研究石锤吗？',
    'Are you sure you want to cancel crafting Plank?': '你确定要取消制作木板吗？',
    'Mining': '采矿',
    'If we dig deep enough maybe there is something nice?': '如果我们挖得足够深，也许有一些不错的东西？',
    'Barracks': '军营',
    'Agriculture': '农业',
    'Bigger fire': '更大的火',
    'Buff production': '抛光生产',
    'Can we hide our goods somewhere?': '我们可以把货物隐藏在某个地方吗？',
    'Cooking': '烹饪',
    'Fish food': '鱼食',
    'Could we make our fire bigger and last for longer?': '我们可以让我们的火更大，持续更久吗？',
    'Forestry': '林业',
    'How can we make those of us more aggressive less of a threat to others?': '我们怎样才能使我们这些人更具侵略性而不是对他人构成威胁呢？',
    'Human resources': '人力资源',
    'Hunting': '狩猎',
    'If others have resources we need maybe we could trade with them?': '如果其他人有我们需要的资源，也许我们可以与他们交易？',
    'Is it possible to lure more fish?': '是否有可能吸引更多的鱼？',
    'Is it possible to produce planks even faster?': '是否有可能更快地生产木板？',
    'Is there any reason why trees grow out of dirt?': '树木长出泥土有什么理由吗？',
    'Management': '管理',
    'Mathematics': '数学',
    'Maybe we can optimize work?': '也许我们可以优化工作？',
    'Maybe we could make some hard decisions which could help us survive?': '也许我们可以做出一些可以帮助我们生存的艰难决定？',
    'Maybe we could rearrange buildings?': '也许我们可以重新安排建筑物？',
    'Maybe we could redesign our pickaxes?': '也许我们可以重新设计我们的镐？',
    'Pickaxe design': '镐头设计',
    'Prerequisites': '先决条件',
    'Prospecting for ore': '勘探矿石',
    'Stash': '贮藏',
    'There must be something useful under all this dirt': '这堆土下面一定有什么有用的东西',
    'Trade': '贸易',
    'Urban planning': '城市规划',
    'Weather': '天气',
    'What if hunted became the hunter?': '如果被猎者变成了猎人?',
    'What if huts were bigger?': '如果小屋更大呢?',
    'What if we calculate things first?': '如果我们先计算呢?',
    'What would happen if we heat up raw food?': '如果我们加热生的食物会发生什么?',
    'Why should we risk looking for food in the forest if we can grow it it the open?': '如果我们可以在森林里露天种植食物，我们为什么要冒险在森林里寻找食物呢?',
    'Would it be good to know the weather in advance?': '提前知道天气会好吗?',
    'Would people work better if we give them better tools?': '如果我们给人们提供更好的工具，他们会工作得更好吗?',
    'Are you sure you want to unlock researching Management?': '您确定要解锁研究管理吗?',
    'Specialised production': '专业生产',
    'Trade routes': '贸易路线',
    'Trade Routes': '贸易路线',
    'Is it possible to attract more merchants?': '有可能吸引更多的商人吗?',
    'Can we specialise in crafting one thing to do it better and faster?': '我们能专注于制造一件事来做得更好更快吗?',
    'Stone axe researched': '石斧已研究',
    'Are you sure you want to unlock researching Bigger fire?': '你确定要解锁研究更大火吗？',
    'Alcohol': '酒精',
    'Are you sure you want to unlock researching Human resources?': '您确定要解锁研究人力资源吗？',
    'Are you sure you want to unlock researching Mathematics?': '你确定要解锁研究数学吗？',
    'Are you sure you want to unlock researching Mortar?': '你确定要解锁研究迫击炮吗？',
    'Are you sure you want to unlock researching Sawmill?': '你确定你要解锁研究锯木厂？',
    'Could we use dead animals fur in our advantage?': '我们能否利用死去的动物皮毛？',
    'Would it boost our moods if we took some time to have fun??': '如果我们花一些时间玩得开心会增强我们的情绪吗？',
    'Mathematics not researched!': '数学未研究！',
    'Mining not researched!': '矿业未研究！',
    'Agriculture researched': '农业已研究',
    'Bow researched': '弓箭已研究',
    'Church unlocked': '教堂已解锁',
    'Cotton planting unlocked': '棉花种植解锁',
    'Cotton researched': '棉花已解锁',
    'Farm invented': '农场已发明',
    'Field unlocked': '农田已解锁',
    'Fire researched': '火已解锁',
    'Fisher\'s hut invented': '渔民小屋已发明',
    'Fishing researched': '钓鱼已研究',
    'Foresight level increased': '预见等级提高',
    'Foresight researched': '预见已研究',
    'Forest management unlocked': '森林管理已解锁',
    'Forester invented': '护林员已发明',
    'Forestry researched': '林业已研究',
    'Human resources invented': '人力资源已发明',
    'Mathematics researched': '数学已研究',
    'Mathematics will permanently affect Construction with +10% of its base power': '数学将永久影响建筑，其基础能力为+ 10％',
    'Mortar researched': '砂浆已研究',
    'New King will affect all buildings with +100% of their base power for 0 days': '新国王将影响所有建筑物，其基础能力为+ 100％，持续0天',
    'New research projects unlocked': '新的研究项目已解锁',
    'New resource discovered: Copper': '发现新资源：铜',
    'New resource discovered: Cut stone': '发现新资源：石材',
    'New resource discovered: Wheat': '发现新资源：小麦',
    'Scientific method researched': '科学方法已研究',
    'Sea unlocked': '海洋已解锁',
    'Shrine unlocked': '神社解锁',
    'Stone shovel researched': '石铲已研究',
    'Urban planning researched': '城市规划已研究',
    'We now can predict weather': '我们现在可以预测天气',
    'Weather researched': '天气已研究',
    'You can always start it again from the top right settings menu': '您可以从右上角的设置菜单重新打开它',
    'today': '今天',
    'Weather forecast': '天气预报',
    'Stone spear not researched!': '石矛没有研究!',
    'Stone pickaxe not researched!': '石镐没有研究!',
    'Stone hammer not researched!': '石锤没有研究!',
    'Stone axe not researched!': '石斧没有研究!',
    'Hunting not researched!': '狩猎没有研究!',
    'Could we use wind to do hard work for us?': '我们能利用风为我们做艰苦的工作吗?',
    'Cooking not researched!': '烹饪没有研究!',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //工艺
    '': '',
    '': '',
    '': '',

    //杂项
    'Close': '关闭',
    'CLOSE': '关闭',
    'day': '天',
    'clear': '清除',
    'CANCEL': '取消',
    'Import save': '导入存档',
    'loaded': '已加载',
    'Import': '导入',
    'HARD RESET': '硬复位',
    'Hard Reset': '硬复位',
    ' buildings': ' 建筑',
    'CONFIRM': '确认',
    'Copy to clipboard': '复制到剪切板',
    'NEXT': '下一条',
    'PREVIOUS': '上一条',
    'YES': '是',
    'NO': '不',
    'OK': '好的',
    'Options': '选项',
    'Other': '其它',
    'pause game': '暂停游戏',
    'Search': '搜索',
    'save logs': '保存日志',
    'sound on/off': '声音 开/关',
    'sound volume': '音量',
    'Update': '更新',
    'Villager Kings v1.': '土皇帝 v1.',
    'Village': '村庄',
    'You will still be able to load game from exported save.': '您仍然可以从导出的存档中加载游戏进度。',
    'auto save on/off': '自动保存 开/关',
    'auto save period': '自动保存间隔',
    'Buildings number limit is now added to build window': '建筑物数量限制现在已添加到建筑窗口中',
    'Export save': '导出存档',
    'minutes': '分',
    'nutrition': '营养',
    'Resources': '资源',
    'Royal perks': '皇家福利',
    'Are you sure you want to hard reset your progress?': '您确定要硬复位您的游戏进度吗?',
    'Choose how many Royal Points you would like to buy': '选择你想买多少皇家点数',
    'Decreased brushwood fuel cost and increased brushwood energy': '降低了原木燃料成本，提高了原木能源',
    'heating energy': '热量能源',
    'saved': '已保存',
    'Build': '建造',
    'All': '全部',
    'building power': '建筑力量',
    'Arrange': '排列',
    'Buildings': '建筑',
    'Demolish': '拆除',
    'famine': '饥荒',
    'Filter': '过滤',
    'food nutrition': '食物营养',
    'happiness effects': '幸福度影响',
    'heating fuel': '加热燃料',
    'Tutorials have been enabled': '教程已启用',
    'This should only be done if you have backup save or want to start from the beginning.': '只有在您有备份存档或希望从头开始时才应该这样做。',
    'Implemented new extended reserver that can define different limit for most of the consumers': '实现了新的扩展储量，可以为大多数使用者定义不同的限制',
    'permanent royal upgrades': '永久皇家升级',
    'royal points,': '皇家点数,',
    'This will remove ALL progress and saved game (except settings and tutorial state).': '这将删除所有进度和游戏存档（设置和教程状态除外）。',
    'Display moving progress bars (on) or just text (off': '显示移动进度条（打开）或仅显示文本（关闭',
    'Gatherer': '采集者',
    'gathering food': '收集食物',
    'gather resources': '收集资源',
    'Stop': '停止',
    'Stores selected type of resources': '存储选定类型的资源',
    'weather multiplier: -': '天气加成: -',
    'occupants: 1/': '居住者: 1/',
    'occupants: 2/': '居住者: 2/',
    'last find: Berry': '最后发现:浆果',
    'last find: Nothing': '最后发现:无',
    'last find: Log': '最后发现：木头',
    'last find: Stone': '最后发现：石头',
    'last find: Wheat': '最后发现：小麦',
    'last find: Brushwood': '最后发现：灌木',
    'SKIP TUTORIAL': '跳过教程',
    'and Gatherer that collects various resources when wandering in the forest. Gatherer has two operating modes': '和采集者在森林里游荡时收集各种资源。 采集者有两种工作模式',
    'At the workshop workers can research new things or build complex things': '在工作台，工人可以研究新事物或制造复杂的东西',
    'food nutrition: -': '食物营养: -',
    'Worker working here can either focus on looking for food or useful and sometimes rare resources': '在这里工作的工人要么专注于寻找食物，要么专注于寻找有用的，有时甚至是稀有的资源',
    'In the forest you have two working buildings': '在森林里，你有两座工作类型的建筑',
    'Logger\'s hut that cuts forest trees and produces logs': '伐木工小屋，用来砍伐森林树木和生产原木',
    'waiting for warehouse space': '等待仓库空间',
    'There are two icons on both sides of building name.': '建筑名称的两侧有两个图标。',
    'To the left there is details icon. If you hover over it,': '左边是详细信息图标。如果你悬停在它上面，',
    'To the right you can see a cog icon which allows you to stop and start production by hiring or firing worker': '在右边你可以看到一个齿轮图标，它允许你停止和开始生产雇用或解雇工人',
    'a tooltip with more technical details regarding a building will popup (not active during tutorial),': '将弹出一个工具提示，其中包含关于建筑物的更多技术细节(在教程期间不活动)，',
    'Second one allows you to set buildings to be demolished by free worker': '第二种允许你设置由自由工人拆除的建筑',
    'In future you will discover many more types of building to build.': '将来你会发现更多类型的建筑需要建造。',
    'Above buildings you can see \'Build\' and \'Demolish\' buttons.': '在建筑物上方，你可以看到“建造”和“拆除”按钮。',
    'First one opens a window with all buildings you can build in this region.': '首先，打开一个窗口，里面有你可以在这个地区建造的所有建筑。',
    'You will receive small portion of resources used to build demolished building': '拆毁建筑物时，你将获得一小部分资源用于建造',
    'Now let\'s order your people to build more gatherers and continue to the \'Resources\' tab in the left menu': '现在让我们命令你的员工建立更多收集者，并继续点击左侧菜单中的“资源”选项卡',
    'FINISH': '完成',
    'Very primitive shelter but keeps rain and cold away': '非常原始的避难所，但可以抵御雨水和保暖',
    'heating required': '需要加热',
    'RAW': '原始',
    'TOOLS': '工具',
    'used by': '用于',
    'To the right there are two additional icons present for each resource': '在右侧，每个资源都有两个额外的图标',
    'To really start progressing you should work towards building Workshop in the village which will open new opportunities': '要真正开始进步，你应该努力在村里建一个车间，这将打开新的机会',
    'That\'s all for the basics.': '这些都是基本的。',
    'Storage can be extended by building warehouses in the village': '仓储可以通过在村里建仓库来扩展',
    'Second icon toggles which resources should be highlighted in the game header': '第二个图标切换哪些资源应该突出显示在游戏头部',
    'PROCESSED': '已处理',
    'Player initiated action can on the other hand use reserved resources': '另一方面，玩家发起的动作可以使用预留资源',
    'Next to the resource icon there is current amount that you have and storage limit for that resource.': '资源图标旁边是您拥有的当前金额和该资源的存储限制。',
    'keep in mind that some actions like for example invasion can still reduce resources below reserved amount!': '请记住，某些操作（例如入侵）仍然可以减少低于预留金额的资源！',
    'In this tab you can browse all of the resources that you have discovered': '在此选项卡中，您可以浏览已发现的所有资源',
    'In the header you can highlight up to 7 resources to know their amounts in any tab of the game': '在标题中，您可以突出显示最多7个资源，以便在游戏的任何标签中了解其数量',
    'First one allows you to set amount that will be reserved and no automated action can use them': '第一个允许您设置将被保留的数量，并且没有自动操作可以使用它们',
    'Welcome to this quick tutorial that will guide you through basic controls of Villager Kings': '欢迎阅读本快速教程，它将指导您完成土皇帝的基本控制',
    '1. Population of your village/max population': '1.你的村庄人口/最大人口',
    '2. Free workers that can be assigned to work': '2.可以分配到工作岗位的空闲工人',
    '3. Size of your empty land where you can build': '3.您空闲土地的大小，你可以建立建筑',
    '4. Size of your whole village (all regions': '4.整个村庄的规模（所有地区',
    '5. Your people happiness, which will influence their productivity': '5.你的人民幸福度，这将影响他们的生产力',
    'Above your buildings you can see most important metrics for current region.': '在您的建筑物上方，您可以看到当前区域的最重要指标。',
    'Currently in your village there are only Huts which produce workers for your village.': '目前在您的村庄里只有棚屋为您的村庄生产工人。',
    'First thing you need to focus on is to make sure that your people will survive winter.': '您需要关注的第一件事是确保您的员工能够度过冬天。',
    'For village those are': '对于村庄来说那些',
    'Good luck!': '祝你好运！',
    'Housing buildings cannot be stopped and require constant supply of food, fuel (in winter) and clothes': '住房建筑无法停止，需要不断供应食物，燃料（冬季）和衣服',
    'In the middle of the village region you can see your buildings. There are many different types of buildings.': '在村庄中间，您可以看到您的建筑物。 有许多不同类型的建筑物。',
    'New King will affect all buildings with +100% of their base power for 90 days': '新国王将在90天内影响所有建筑物的基础能力+ 100％',
    'Remember that winter is not the only threat to your people!': '请记住，冬天不是对你的人民的唯一威胁！',
    'Right now we are in the village tab and using top menu you can navigate between village regions': '现在我们在村庄标签中，使用顶级菜单，您可以在村庄区域之间导航',
    'Some of them produce items, others consume them to produce more advanced items.': '他们中的一些人生产产品，另一些人消费它们来生产更高级的产品。',
    'temporary effects': '暂时性效应',
    'That\'s all here for now let\'s move into the Forest region': '现在就讲到这里，让我们进入森林地区',
    'To the left you can see navigation menu that will allow you to browse tabs representing different aspects of your village': '在左边，您可以看到导航菜单，它将允许您浏览代表村庄不同方面的选项卡',
    'using top menu and continue the tutorial there': '使用顶部菜单并在那里继续教程',
    'Villager Kings': '土皇帝',
    'Welcome to': '欢迎来到',
    'Will you manage to lead your people to greatness?': '你能带领你的人民走向伟大吗?',
    'You start as a leader of a small village.': '你从一个小村庄的领导者开始。',
    'You will need to increase food production and have some wood to heat houses.': '你将需要增加粮食产量和一些木材来加热房屋。',
    '(will use it\'s own limit number if enabled': '(将使用它自己的限制号码，如果启用',
    'Crafting': '工艺',
    'Exceptions': '例外',
    'Log management': '日志管理',
    'reserved amount': '保留金额',
    'SAVE': '保存',
    'chopping trees': '砍树',
    'transporting log': '运输日志',
    'waiting for trees': '等待树',
    'Construction': '建造',
    'constructing Workshop': '正在建造工作台',
    'Missing 10 Plank': '缺少10木板',
    'Missing 5 Cut stone': '缺少5石材',
    'constructing Hut': '正在建造棚屋',
    'Missing 10 Brushwood': '缺少10灌木',
    'occupants: 0/': '居住者: 0/',
    'Research': '研究',
    'nothing': '无',
    'nothing to research': '没有什么可以研究的',
    'Research points: 0/': '研究点: 0/',
    'Researching': '正在研究',
    'Researching unlocked': '研究已解锁',
    'SCIENCE': '科学',
    'Scientific method': '科学方法',
    'show finished': '显示完成',
    'TECHNOLOGY': '技术',
    'MILITARY': '军事',
    'Maybe there is something we don\'t know about yet?': '也许有些事情我们还不知道?',
    'GENERAL': '常规',
    'Crafting unlocked': '工艺已解锁',
    'craft': '工艺',
    'AGRICULTURE': '农业',
    'ALL': '全部',
    'amount': '数量',
    'continuous': '连续',
    'Cost': '成本',
    'Cut Stone': '石材',
    'Difficulty': '困难',
    'Leather': '皮革',
    'Orders': '队列',
    'OTHER': '其它',
    'Plank': '木板',
    'Recipes': '配方',
    'selected amount': '已选择数量',
    'until X available': '直到X可用',
    'Are you sure you want to unlock researching Scientific method?': '你确定要开启科学研究方法吗?',
    'requires 5 more research points': '需要5个研究点',
    'researching': '研究中',
    'and Wonders and their effects will be deleted.': '和奇迹及其影响将被删除。',
    'Are you sure you want to soft reset your progress?': '您确定要软重置进度吗？',
    'You will start from the beginning and all progress except for': '你将从头开始，所有游戏进度除了',
    'heating': '加热',
    'Missing 20 Brushwood!': '缺少20个灌木！',
    'Brushwood management': '灌木管理',
    'Missing 10 Stone!': '缺少10石头',
    'Very primitive shelter but keeps rain and cold away. Houses 2 villagers': '非常原始的庇护所，但可以避雨和御寒。可以容纳2村民',
    'cost': '成本',
    'At the workshop workers can do research projects or build complex things': '在工作台里，工人们可以做研究项目或建造复杂的东西',
    'Stone management': '石头管理',
    'Clothes': '衣服',
    'Plank management': '木板管理',
    'Order queue is full': '制作队列已满',
    'gathering resources': '收集资源',
    'transporting': '运输',
    'gather food': '收集食物',
    'crafting Plank': '制作木板',
    'cancel crafting': '取消制作',
    'research': '研究',
    'crafting': '工艺',
    'nothing to craft': '没有东西可制作',
    'Auto saved': '自动保存',
    'Hut clothing': '小屋衣服',
    'Stone Pickaxe': '石镐',
    'Stone pickaxe researched': '石镐已研究',
    'can produce': '可以生产',
    'No workshop set to research.': '没有工作台设置为研究',
    'Too many highlighted resources': '突出显示的资源过多，最多7种',
    'constructing Loggers hut': '建造伐木工小屋',
    'Couldn\'t unlock construction. Not enough free workers.': '无法解锁施工。 空闲工人不够。',
    'Gatherer can find all kinds of useful things in the forest.': '收集者可以在森林中找到各种有用的东西。',
    'Loggers cut trees in the forest': '伐木工在森林里砍伐树木',
    'They can look for either food or resources': '他们可以寻找食物或资源',
    'Invasion': '入侵',
    'INVASION': '入侵',
    'Management researched': '管理已研究',
    'Management tab unlocked': '管理标签页已解锁',
    'We have been plundered': '我们被掠夺了',
    'alcohol': '酒精',
    'allow fur when no clothes available': '没有衣服的时候允许穿皮草',
    'Effects': '效果',
    'food': '食物',
    'General': '常规',
    'General Management': '常规管理',
    'Rations': '给养',
    'show total food nutrition in village tab': '显示总食物营养在村庄标签',
    'Cannot unlock production of Construction. Number of free workers': '无法解锁建筑生产。空闲工人数量',
    'Cannot unlock production of Loggers hut. Number of free workers': '无法解锁伐木工小屋的生产。空闲工人数量',
    'Cannot unlock production of Gatherer. Number of free workers': '无法解锁收集者的生产。 空闲工人数量',
    'Cannot unlock production of Fishers hut. Number of free workers': '无法解锁渔民小屋的生产。 空闲工人数量',
    'Calendar researched': '日历已研究',
    'We are now able to track years and seasons': '我们现在能够追踪年份和季节',
    'Are you sure you want to unlock researching Trade?': '你确定要开启研究贸易吗?',
    'Advanced ore processing': '先进的矿石加工',
    'Advanced prospecting': '先进的勘探',
    'Animals': '动物',
    'Bread': '面包',
    'Built smithy': '建造铁匠铺',
    'Could we get precious resources from under the ground?': '我们能从地下获得宝贵的资源吗？',
    'Could we make fabric using cotton?': '我们可以用棉布制作面料吗？',
    'Could we reuse what animals produce?': '我们能重复利用动物生产的东西？',
    'Crafted': '精心制作',
    'Cut stone': '石材',
    'enable automated work management for some buildings': '为一些建筑物实现自动化工作管理',
    'Fabric': '织品',
    'Faith': '信仰',
    'Faith shield': '信仰之盾',
    'Fertility': '生殖力',
    'Fertilizer': '肥料',
    'Fish food researched': '鱼食已研究',
    'Flour': '面粉',
    'Fuel': '燃料',
    'How can me make new clothes?': '我怎样才能做新衣服?',
    'Is it possible to breed animals near farms?': '有可能在农场附近饲养动物吗?',
    'Is there anything else to find?': '还有什么要找的吗?',
    'Marketplace invented': '市场发明',
    'Master prospecting': '掌握勘探',
    'Maybe we could use logs to defend ourselves?': '也许我们可以用木头来自卫?',
    'Meat Soup': '肉汤',
    'Meat soup': '肉汤',
    'Metallurgy': '冶金',
    'Nature': '自然',
    'New resource discovered: Fish food': '新发现的资源:鱼类食物',
    'None': '无',
    'offering': '提供',
    'Ore processing': '矿石加工',
    'Pit mine': '矿井',
    'Prayers': '祈祷',
    'Preach': '传道',
    'Religion': '宗教',
    'Religions': '宗教',
    'save imported': '存档已导入',
    'Tailoring': '裁剪',
    'Technology': '技术',
    'There must be something even more valuable under the ground?': '地下一定有更值钱的东西吧?',
    'Trade researched': '贸易已研究',
    'Vegetable Soup': '蔬菜汤',
    'War': '战争',
    'We shall spread our beliefs to others': '我们应该把我们的信仰传播给别人',
    'What about heating other ores?': '那加热其他矿石呢?',
    'What happens if we heat ore in fire?': '如果我们用火加热矿石会发生什么?',
    'What would happen if we mix two metals?': '如果我们混合两种金属会发生什么?',
    'Wooden defences': '木制的防御',
    'storage': '存储',
    'Mountains': '山地',
    'NONE': '无',
    'Fort': '要塞',
    'Field': '田地',
    'permanent effects': '永久效果',
    'Plateau': '高原',
    'prayers': '祈祷',
    'Sea': '海洋',
    'Shrine': '圣地',
    'waiting for fuel': '等待燃料',
    'fish': '鱼',
    'fish food': '鱼食',
    'fishing': '钓鱼',
    'hire worker': '雇佣工人',
    'produce fish food': '生产鱼食',
    'School of fish': '鱼群',
    'Stonehenge': '巨石阵',
    'Stonehenge construction': '巨石阵建筑',
    'fire worker': '解雇工人',
    'add materials': '添加材料',
    'add fish food': '添加鱼食',
    'BARLEY': '大麦',
    'building level': '建筑等级',
    'Combine': '组合',
    'COTTON': '棉花',
    'Cotton field': '棉田',
    'cutting  plank': '切割木板',
    'fallow': '休耕',
    'Farm': '农场',
    'Forester': '护林人',
    'growing difficulty': '成长困难',
    'Hay': '干草',
    'HAY': '干草',
    'HOP': '啤酒花',
    'Hunter lodge': '猎人小屋',
    'hunting': '狩猎',
    'last find: Mushroom': '最后发现:蘑菇',
    'mining stone': '开采石头',
    'planting trees': '种树',
    'Quarry': '采石场',
    'size': '大小',
    'Split': '分割',
    'stash size': '储备规模',
    'stone': '石头',
    'Temperature': '温度',
    'waiting for fur': '等待皮毛',
    'waiting for stone': '等待石头',
    'weather multiplier': '天气加成',
    'Weather: sun': '天气: 晴朗',
    'WHEAT': '小麦',
    'workers: 1/': '工人: 1/',
    'working': '工作',
    'yield multiplier': '收益加成',
    'Temperature: -': '温度: -',
    'Weather: storm': '天气: 风暴',
    'Weather: snow': '天气: 下雪',
    'Weather: sun': '天气: 晴朗',
    'Weather: wind': '天气: 大风',
    'Weather: clouds': '天气: 多云',
    'Weather: rain': '天气: 下雨',
    'Upgrade to level': '升级到等级',
    'Are you sure you want to change religion?': '你确定要改变宗教吗?',
    'Are you sure you want to unlock researching Fabric?': '您确定要解锁研究织品吗？',
    'Army effects': '军队效果',
    'building': '建筑',
    'Buildings effects': '建筑效果',
    'Cut trees if': '砍树如果',
    'duration': '持续时间',
    'effect': '效果',
    'Effects Management': '效果管理',
    'Forest bigger than': '森林大于',
    'Forest Management': '森林管理',
    'forest smaller than': '森林小于',
    'free land bigger than': '空闲土地大于',
    'name': '名称',
    'permanent': '常驻',
    'Plant trees if': '种树如果',
    'fetching wheat': '取小麦',
    'waiting for fish': '等鱼',
    'Advanced prospecting not researched!': '没有研究过高级勘探！',
    'no enough free land': '没有足够的空闲土地',
    'Blessing': '祝福',
    'May everything go according to our plans': '愿一切都按照我们的计划进行',
    'Not enough faith for this prayer!': '对这个祷告没有足够的信仰！',
    'Our faith will protect us from harm': '我们的信仰将保护我们免受伤害',
    'Buy Royal points': '购买皇家点数',
    'Call to arms': '武装召唤',
    'Family jewels': '传家宝',
    'Heritage': '遗产',
    'King of the forest': '森林之王',
    'King of the people': '人民之王',
    'King of the war': '战争之王',
    'Motivation speech': '动机演讲',
    'People love you unconditionally. You start with House unlocked and built instead of huts (awarded after any soft reset or abdication': '人们无条件地爱你。 你可以从房屋解锁并建造而不是棚屋（在任何软复位或退位后获得）',
    'royal points.': '皇家点数。',
    'Royal prophecy': '皇家预言',
    'Unite with the people': '与人民团结起来',
    'Usages: unlimited': '用途：无限制',
    'Use your royal position to motivate people to harder work. 25% production upgrade for all buildings for 1 year (single use': '利用你的王室职位来激励人们更加努力工作。 所有建筑物的生产升级25％，为期1年（单次使用',
    'War is your game. You start with military unlocked and small army (awarded after any soft reset or abdication': '战争是你的游戏。 你从军事解锁和小军队开始（在任何软复位或退位后获得',
    'We will fight till the last of us drops dead. You can convert up to 10 villagers to militia (single use': '我们将战斗直到我们最后一个人死亡。 您最多可以将10名村民转为民兵（单次使用',
    'You can use them to acquire special upgrades.': '您可以使用它们获取特殊升级。',
    'You have': '你有',
    'You rule everything in the forests. You start with a few forest buildings unlocked (awarded after any soft reset or abdication': '你统治森林里的一切。 您可以从一些解锁的森林建筑开始（在任何软复位或退位后获得',
    'You step down from your throne and live with others. Permanent 20% upgrade to all buildings (persists through soft resets and abdications': '你从宝座上下台，和别人一起生活。 永久20％升级到所有建筑物（通过软重置和退役持续存在',
    'Your predecessors left you with more riches. You start with extra resources (awarded after any soft reset or abdication': '你的前辈给你留下了更多的财富。 您可以从额外的资源开始（在任何软复位或退位后获得',
    'Your predecessors ruled better. You start with extra building (awarded after any soft reset or abdication': '你的前任统治得更好。 您从额外的建筑开始（在任何软复位或退位后获得',
    'Your royal blood allows prophets to look into the future. Unlocks certain research for each perk level (awarded immediately and after any soft reset or abdication': '你的王室血液允许先知展望未来。 为每个额外水平解锁某些研究（立即授予以及在任何软复位或退位后获得',
    'Village buildings': '村庄建筑',
    'hide finished': '隐藏已完成',
    'Underground city': '地下城',
    'happiness effects: -': '幸福度效果: -',
    'crafting Cut stone': '制作石材',
    'constructing Warehouse': '仓库建设中',
    'built in year': '建造年代',
    'abdicate': '退位',
    'New Year!': '新年快乐！',
    'Bigger fire researched': '更大的火已研究',
    'Automated work management available in management tab': '管理选项卡中提供自动化工作管理',
    'Human resources researched': '人力资源已研究',
    'Are you sure you want to skip tutorial?': '您确定要跳过教程吗?',
    'heating fuel: -': '加热燃料: -',
    'New resource discovered: Apple': '发现新资源：苹果',
    'New resource discovered: Grape': '发现新资源：葡萄',
    'Army': '军队',
    'Church': '教堂',
    'crafting Stone spear': '制作石矛',
    'Crafting tab orders will now display how many workshops are crafting particular item': '工艺标签页队列现在将显示制作特定项目的工作坊数量',
    'crafting Wooden shield': '制作木盾',
    'Critical forest size!': '临界森林大小！',
    'Daily consumption': '每日消费',
    'Forest low size warnings will now display only when forestry is not researched': '只有在不研究林业的情况下，才会显示森林小面积警告',
    'Increased hay required by animals during winter': '动物在冬天需要更多的干草',
    'Leather Armor': '皮护甲',
    'Manufacture moved closer in the research tree and has cost decreased': '制造在研究树上的位置越来越近，成本也降低了',
    'Mint now requires gold and silver to make coins': '造币厂现在需要黄金和白银来制造钱币',
    'Nutrition': '营养',
    'Nutrition display has been moved to header (might cause highlighted items to overflow': '营养显示已移至页眉(可能导致突出显示的项溢出',
    'Offering': '提供',
    'Removed horse cost from expeditions': '从探险中扣除马匹费用',
    'Smithy can no longer be blessed': '铁匠铺不再受祝福',
    'Warehouse building size increased (resource storage stays the same': '仓库建筑规模增加(资源存储保持不变)',
    'Warehouses can be combined and split': '仓库可以合并和拆分',
    'Wooden Shield': '木盾',
    'Archer -': '弓箭手 - ',
    'capacity': '容量',
    ' -': ' -',
    ' 10/': ' 10/',
    '1 x Archer': '1 x 弓箭手',
    '1 x Light Cavalry': '1 x 轻骑兵',
    '1 x Militia': '1 x 民兵',
    '1 x Spearman': '1 x 枪兵',
    '1 x Swordsman': '1 x 剑士',
    'Coal': '煤',
    'coal': '煤',
    'CONQUER': '征服',
    'Conquer your enemies and claim their land': '征服你的敌人并夺取他们的土地',
    'DEFEND': '防守',
    'defense': '防御',
    'DIVERSION': '转移',
    'durability: 50/': '耐久: 50/',
    'EXPEDITION': '探险',
    'GARRISON': '驻军',
    'Leather armor': '皮甲',
    'Light cavalry -': '轻骑兵 -',
    'Look for new land, other villages and treasures': '寻找新的土地，其他村庄和宝藏',
    'Militia -': '民兵 - ',
    'MISSIONS': '任务',
    'MISSIONS IN PROGRESS': '进展中的任务',
    'no recruits': '没有新兵',
    'PLUNDER': '掠夺',
    'Plunder your enemies': '掠夺你的敌人',
    'Protect your land and reduce chance for being invaded': '保护你的土地，减少被入侵的机会',
    'RECRUITS': '新兵',
    'Spearman -': '枪兵 -',
    'SPY': '间谍',
    'Stats (per soldier': '统计数据（每名士兵',
    'Swordsman -': '剑士 -',
    'TRAIN': '训练',
    'Train your troops to temporary increase their power': '训练你的部队临时增加他们的力量',
    'Training square': '训练广场',
    'Try to find out military strength of the enemy': '试着找出敌人的军事实力',
    'We need to bring enemy power down': '我们需要降低敌人的力量',
    'Wooden shield': '木盾',
    'Wooden tower': '木塔',
    'bad weather': '坏天气',
    'New tools': '新工具',
    'stopped': '已停止',
    'New tools will affect Farm with +5% of its base power for 360 days': '新工具将影响农场，其基本加成为+ 5％，持续360天',
    'Not enough unemployed people to recruit!': '没有足够的失业人员可以招聘!',
    'Longhouse': '长屋',
    'Could we house multiple families in one building?': '我们可以在一栋楼里安置多个家庭吗？',
    'Maybe we could use stone to defend ourselves?': '也许我们可以用石头来保卫自己？',
    'Stone defences': '石头防御',
    'show food nutrition in the header': '在顶部显示食物营养',
    'constructing Forester': '建造护林人',
    'deconstructing Quarry': '建造采石场',
    'Deconstruction': '建造',
    'fetching fur': '获取皮毛',
    'fetching log': '获取木头',
    'fetching stone': '获取石头',
    'Geologist': '地质学家',
    'House clothing': '室内服装',
    'last find: nothing': '最后发现:无',
    'looking for ores': '寻找矿石',
    'no more resources': '没有更多的资源了',
    'Shark': '鲨鱼',
    'sharks': '鲨鱼',
    'Underground city construction': '地下城市建设',
    'last find: Copper ore deposit': '最后发现:铜矿床',
    'last find: Coal deposit': '最后发现:煤炭矿床',
    'Cannot unlock production of Pit mine. Number of free workers': '无法解锁矿井生产。空闲工人人数',
    'Cannot unlock production of Workshop. Number of free workers': '无法解锁车间的生产。空闲工人人数',
    'Allows workers to mine ores': '允许工人开采矿石',
    'Cuts stone out of mountains': '从山上开采石头',
    'Looks for useful rocks': '寻找有用的岩石',
    'Mountains buildings': '山区建筑',
    'production input': '生产投入',
    'production output': '生产产量',
    'Shapes stones for building': '建筑石材',
    'Brews delicious beer': '酿造美味的啤酒',
    'Extracts and ferments grape juices': '提取和发酵葡萄汁',
    'Farm allows workers to work on fields, orchard and pastures': '农场允许工人在田野、果园和牧场上工作',
    'Field buildings': '农田建筑',
    'Fishers catch fish in the sea': '渔夫在海里捕鱼',
    'Forest buildings': '森林建筑',
    'Forester can plant new trees and control natural growth of the forest': '林务员可以种植新的树木，控制森林的自然生长',
    'Hunts animals for meat and fur': '猎取动物的肉和皮毛',
    'Orchard': '果园',
    'Plateau buildings': '高原建筑',
    'Sawmill cut logs into planks': '锯木厂把原木锯成厚木板',
    'Sea buildings': '海上建筑',
    'Turns furs into leather': '把毛皮变成皮革',
    'Various crops can be grown here (Farm required to work on fields': '这里可以种植欠条作物(农场需要在田里耕作)',
    'Various fruit trees and bushes can be grown here (Farm required to work on orchards': '这里可以种植各种果树和灌木(农场需要在果园工作)',
    'Windmill turns wheat into flour': '风车把小麦变成面粉',
    'Bakes bread from flour': '用面粉烤面包',
    'Bigger and more durable shelter. Houses 6 villagers': '更大更耐用的庇护所。可以容纳6个村民',
    'Complex hidden tunnels allow us to hide some resources in case of invasion': '复杂的隐藏隧道可以让我们隐藏一些资源，以防入侵',
    'Consume wine and beer but increase happiness': '多喝葡萄酒和啤酒，能增加幸福感',
    'Fort buildings': '要塞建筑',
    'Housing for troops': '部队住房',
    'Marketplace': '市场',
    'Meeting place where villagers can relax and cheer up': '村民们可以放松和振作的聚会场所',
    'Place for prayer and offerings': '祈祷和献祭的地方',
    'Place for trading with other villages': '与其他村庄进行贸易的场所',
    'Place for training recruits': '新兵训练地点',
    'Protective wall around the village to protect against attackers': '村庄周围的防护墙，以防止攻击者',
    'Provide passive defense power': '提供被动防御能力',
    'Stockade': '栅栏',
    'Pickaxe Design': '镐头设计',
    'constructing Pit mine': '建造露天矿',
    'crafting Fuel': '制作燃料',
    'Heavy Armor': '重甲',
    'Cheese': '奶酪',
    'crafting Meat soup': '制作肉汤',
    'crafting Vegetable soup': '制作蔬菜汤',
    'Horse': '马',
    'Herbs': '草药',
    'Chicken': '鸡',
    'Beer': '啤酒',
    'Apple': '苹果',
    'Copper ore': '铜矿石',
    'Cow': '奶牛',
    'Grape': '葡萄',
    'Hop': '啤酒花',
    'Iron ore': '铁矿石',
    'Milk': '牛奶',
    'Pig': '猪',
    'Silver ore': '银矿石',
    'Tin ore': '锡矿石',
    'Life cycle': '生命周期',
    'Expedition': '探险',
    'Diversion': '转移',
    'Defend': '防守',
    'Conquer': '征服',
    'Archer': '弓箭手',
    'Militia': '民兵',
    'Plunder': '掠夺',
    'Soldier prayer': '士兵祈祷',
    'Spearman': '枪兵',
    'Spy': '间谍',
    'START': '开始',
    'Train': '训练',
    'squad defense: 0 /': '小队防御：0 /',
    'squad strength: 0 /': '小队实力：0 /',
    'Sell': '出售',
    'price': '价格',
    'piece price': '单件价格',
    'Plank buy offer': '木板买入报价',
    'Pig buy offer': '猪买入报价',
    'Offers': '报价',
    'offer': '报价',
    'Meat sell offer': '肉类出售报价',
    'Light armor sell offer': '轻甲出售报价',
    'Hop buy offer': '啤酒购买报价',
    'Hay sell offer': '干草出售报价',
    'Hay buy offer': '干草购买报价',
    'Gold ore sell offer': '金矿石出售报价',
    'Filters': '过滤',
    'Buy': '购买',
    'buy/sell': '购买/出售',
    'total price': '总价格',
    'Wheat sell offer': '小麦出售报价',
    'Stone hammer sell offer': '石锤出售报价',
    'Barley sell offer': '大麦出售报价',
    'buy': '购买',
    'BUY': '购买',
    'Fabric sell offer': '面料出售报价',
    'How many': '多少',
    'Leather sell offer': '皮革出售报价',
    'Market offer': '市场报价',
    'Merchant arrived': '商人到了',
    'Pig sell offer': '猪出售报价',
    'Stone axe buy offer': '石斧购买报价',
    'COPPER ORE': '铜矿石',
    'GOLD ORE': '金矿石',
    'IRON ORE': '铁矿石',
    'COAL': '煤',
    'no more coal': '没有更多的煤了',
    'NOTHING': '无',
    'SILVER ORE': '银矿石',
    'Smithy': '铁匠铺',
    'TIN ORE': '锡矿石',
    'waiting for ore selection': '等待选矿',
    'Are you sure you want to mine Coal in this mine?': '你确定要在这个矿山开采煤矿吗？',
    'Are you sure you want to mine Gold ore in this mine?': '你确定要在这个矿山开采金矿石吗？',
    'Are you sure you want to mine Silver ore in this mine?': '你确定要在这个矿山开采银矿石吗？',
    'Are you sure you want to mine Copper ore in this mine?': '你确定要在这个矿山开采铜矿石吗？',
    'Are you sure you want to mine Iron ore in this mine?': '你确定要在这个矿山开采铁矿石吗？',
    'Are you sure you want to mine Tin ore in this mine?': '你确定要在这个矿山开采锡矿石吗？',
    'Coins minting': '钱币铸造',
    'Herbal medicine': '草药医学',
    'Master ore processing': '掌握矿石加工',
    'Maybe we can make our own coins?': '也许我们可以自己制作硬币?',
    'Would we heal faster if we used herbs?': '如果我们使用草药，我们会愈合得更快吗?',
    'Are you sure you want to unlock researching Herbal medicine?': '你确定要解锁研究草药吗？',
    'Are you sure you want to unlock researching Advanced ore processing?': '您确定要解锁研究先进的矿石加工吗？',
    'Advanced ore processing not researched!': '先进的矿石加工未研究过！',
    'Can we smelt any ore we want?': '我们可以闻到我们想要的任何矿石吗？',
    'SELL': '出售',
    'sell': '出售',
    'Sword buy offer': '剑购买报价',
    'Sword sell offer': '剑出售报价',
    'Plank sell offer': '木板出售报价',
    'Meat buy offer': '肉类购买报价',
    'Log buy offer': '木头购买报价',
    'Leather buy offer': '皮革购买报价',
    'Leather armor sell offer': '皮甲出售报价',
    'Hop sell offer': '啤酒出售报价',
    'Fuel buy offer': '燃料购买报价',
    'Fish food buy offer': '鱼食购买报价',
    'Cow buy offer': '奶牛购买报价',
    'Fabric buy offer': '面料购买报价',
    'Are you sure you want to cancel crafting Bread?': '你确定要取消制作面包吗？',
    'Are you sure you want to cancel crafting Fuel?': '你确定要取消制作燃料吗？',
    'Are you sure you want to cancel crafting Meat soup?': '你确定要取消制作肉汤吗？',
    'Are you sure you want to cancel crafting Vegetable soup?': '你确定要取消制作蔬菜汤吗？',
    'for': '花费',
    'Not enough space in barracks for so many recruits': '对于这么多新兵而言，营房空间不足',
    'You cannot start mission without any troops': '没有任何部队你就无法开始执行任务',
    'Coal buy offer': '煤炭购买报价',
    'Copper buy offer': '铜购买报价',
    'Copper ore sell offer': '铁矿石出售报价',
    'Cut stone sell offer': '石材出售报价',
    'Stone spear sell offer': '石矛出售报价',
    'Vegetable soup buy offer': '蔬菜汤购买报价',
    'Vegetable soup sell offer': '蔬菜汤出售报价',
    'Wheat buy offer': '小麦购买报价',
    'Gold ore': '金矿石',
    'Heavy armor': '重甲',
    'Light armor': '轻甲',
    'Longhouse clothing': '长屋服装',
    'Stone tower': '石塔',
    'training': '训练中',
    'harvest': '收获',
    'Hay field': '干草场',
    'Hop field': '啤酒花田',
    'hop growing': '啤酒花生长中',
    'Pasture': '牧场',
    'Wheat field': '小麦田',
    'wheat growing': '小麦生长中',
    'cotton growing': '棉花生长中',
    'Butcher': '屠夫',
    'barley growing': '大麦生长中',
    'Barley field': '大麦田',
    'Are you sure you want to switch field crop type?': '你确定要切换农田作物类型？',
    'All field progress will be lost': '所有农田生长进度都将丢失',
    'harvesting hay': '收货干草',
    'transporting silver ore': '运输银矿石',
    'silver ore': '银矿石',
    'mining silver ore': '开采矿银矿',
    'New tools will affect Pit mine with +5% of its base power for 360 days': '新的工具将影响露天矿其基本加成+ 5％，持续360天',
    'Move': '移动',
    'royal points, permanent royal upgrades and Wonders will be deleted.': '皇家点数，永久皇家升级和奇迹将被删除。',
    'You will be awarded 1 Heritage Points': '您将获得1点遗产点数',
    'reserve ': '保留 ',
    'Manufacture': '制造',
    'wine': '酒',
    'merchant arrival': '商人到来了',
    'sewing  clothes': '缝制衣服',
    'waiting for alcohol': '正在等待酒精',
    'crafting Leather armor': '制作皮甲',
    'bribe merchant (50% chance': '贿赂商人（50％的几率',
    'beer': '啤酒',
    'Spins cotton into fabric': '将棉花纺成面料',
    'Turns animals from pastures into meat': '将动物从牧场变成肉',
    'Many animals can be grown here (Farm required to work on pastures': '许多动物都可以在这里生长（需要从农场到牧场工作',
    '(limit: 3 buildings': '（限制：3建筑',
    'constructing Stone tower': '正在建造石塔',
    'Long building for multiple families. Houses 15 villagers': '多户长屋。可居住15个村民',
    'mining coal': '开采煤炭',
    'Produces clothes from fabric': '用织物生产衣服',
    'producing fish food': '生产鱼食',
    'Provide passive defense power, more durable than wooden tower': '提供被动防御能力，比木塔更耐用',
    'transporting coal': '煤炭运输',
    'transporting fish': '运输鱼',
    'Bread buy offer': '面包购买报价',
    'Copper ore buy offer': '铁矿石购买报价',
    'Silver ore sell offer': '银矿石出售报价',
    'Allow fur when no clothes are available': '没有衣服的时候，允许穿皮草',
    'Display two rows in the header (resources will be displayed in second row': '在顶部显示两行(资源将显示在第二行中)',
    'Enable automated work management for some buildings': '为某些建筑物启用自动化的工作管理',
    'Header management': '顶部管理',
    'Show food nutrition in the header': '在标题中显示食物营养',
    'Show free workers in the header': '在标题中显示空闲工人',
    'Show population in the header': '在标题中显示人口',
    'There is no tutorial for this tab': '这个选项卡没有教程',
    'After geologist is unlocked and built he will start looking for ores deposits which is very slow process.': '地质学家在开锁和建造之后，就会开始寻找矿藏，这是一个非常缓慢的过程。',
    'After sowing is completed your crops will start to grow until Autumn.': '播种完成后，你的庄稼将开始生长直到秋天。',
    'after that they keep growing for several years without any work input.': '在那之后，他们在没有任何工作投入的情况下持续增长了几年。',
    'All animals can be butchered for meat when butcher building is built.': '当屠宰场建成时，动物可以被屠宰作为肉类。',
    'and animals require Hay to eat during winter.': '动物在冬天需要吃干草。',
    'By the sea fishers can catch fish from the sea.': '在海边，渔民可以从海里抓鱼。',
    'Each school of fish has certain number of fish that slowly breed.': '鱼群中有一定数量的鱼在缓慢繁殖。',
    'Each Wonder building adds permanent buff corresponding to it\'s nature.': '每个奇迹建筑都增加了与其自然属性相对应的永久增益。',
    'Field region has many buildings with different mechanics than other regions.': '农田有许多不同于其他地区的建筑物。',
    'Field, Orchard and Pasture buildings require Farm with workers': '农田、果园和牧场建筑需要有工人的农场',
    'Fields yearly cycle starts in spring, after you have selected what type of crops should be planted,': '田地每年的周期从春天开始，在你选择了应该种植哪种作物之后，',
    'Fishers can also produce fish food which will boost fish breeding rate.': '渔民也可以生产鱼类食品，这将提高鱼类的繁殖率。',
    'If no hay is available animals can starve to death.': '如果没有干草，动物就会饿死。',
    'If there are any crops not harvested by the beginning of winter they will wither and will be lost.': '在立冬以前，若有不收的庄稼，就要枯干，归于无有。',
    'If you catch all fish, new school of fish should appear in some time.': '如果你钓完了所有的鱼，不久就会出现新的鱼群。',
    'In this special area Wonder buildings can be constructed.': '在这个特殊的地区可以建造奇迹建筑。',
    'Most mountains buildings require mountains space instead of free land.': '大多数山地建筑需要山地空间，而不是空闲的土地。',
    'On autumn all crops will stop growing and will be ready for harvest performed by Farm workers.': '到了秋天，所有的庄稼都将停止生长，等待农场工人收割。',
    'Once 20 deposits of certain resource has been found Pit Mine can be used to mine it.': '一旦发现某一资源的20个矿床，就可以用坑矿来开采。',
    'Once animals are researched Hunters can try to tame animals for which there is empty pasture space.': '一旦对动物进行了研究，猎人就可以尝试驯服那些没有牧场的动物。',
    'Once they matured they will fruit every year with only harvest work required.': '一旦成熟，它们每年都会结出果实，只需要收割。',
    'Orchards are a bit different. Those also need to be plowed and plants need to be planted,': '果园有点不同。这些也需要耕种和种植，',
    'Pastures allow animals breeding. They require work input for the whole year (chores': '牧场允许动物繁殖。他们需要全年的工作投入(杂务)',
    'Some animals produce animals products like eggs and milk which add to your food supplies.': '有些动物生产动物产品，如鸡蛋和牛奶，增加你的食物供应。',
    'These require much more resources and much more work to be completed.': '这需要更多的资源和更多的工作来完成。',
    'They eat grass and other natural food during other seasons.': '它们在其他季节吃草和其他天然食物。',
    'This mountain area is finite and after the building deplete resources it can be demolished to add empty land instead of back to mountains.': '这个山区是有限的，在建筑耗尽资源后，可以拆除，增加空地，而不是回到山区。',
    'To gain more mountains areas you will need to run expeditions or conquer enemies (Army).': '为了获得更多的山区，你需要进行探险或征服敌人(军队)。',
    'who will work on planting, sowing, harvesting and tending to animals.': '谁将种植,播种、收获和照顾动物。',
    'Wonder building also allows you to abdicate what performs soft reset and additionally award you with Royal Points to spend on Royal perks.': '奇迹建筑也可以让你放弃什么执行软复位，另外奖励您皇家点用于购买皇家特权。',
    'Wonder building and it\'s buff persist through soft resets and abdications.': '奇迹建筑和它的增益坚持通过软重置和退位。',
    'your Farm workers will start plowing the land and then sowing selected crop.': '你的农场工人将开始耕地，然后播种选定的作物。',
    'Apple sell offer': '苹果出售报价',
    'Barley buy offer': '大麦买入报价',
    'Chicken buy offer': '鸡买入报价',
    'Chicken sell offer': '鸡出售报价',
    'Cotton buy offer': '棉花购买报价',
    'Iron buy offer': '铁购买报价',
    'Iron sell offer': '铁出售报价',
    'Stone pickaxe buy offer': '石镐买入报价',
    'Not enough resources to sell': '没有足够的资源可以出售',
    'hay growing': '干草生长中',
    'Working': '工作中',
    'Idle': '闲置',
    'Gold ore buy offer': '金矿石购买报价',
    'Meat soup sell offer': '肉汤出售报价',
    'Mushroom sell offer': '蘑菇出售报价',
    'Tin buy offer': '锡购买报价',
    'Log sell offer': '木头出售报价',
    'Jester': '小丑',
    'You hired jester to entertain you but who knows what can you expect from him? Jester will pick random unlocked resource (except coins) and fill it to max storage. Each time he fills resource or picks already full resource he has 50% chance to pick another one (single use': '你聘请了小丑来招待你，但谁知道你对他有什么期望？ 小丑将挑选随机解锁资源（硬币除外）并将其填充到最大存储空间。 每次他填充资源或选择已经全部资源时，他有50％的机会选择另一个（单次使用',
    'Heritage points: 0/': '遗产点数：0/',
    'Heritage points are permanent and points spent in any run will be returned after reset, abdication or ascension. Heritage Points will be lost after hard reset.': '遗产点是永久性的，任何运行中花费的点数将在重置，退位或提升后返回。 硬重置后遗产点将丢失。',
    'Buy mountains (10 mountains for 1 Heritage Point': '购买山（10个山花费1遗产点',
    'Buy land (20 land for 1 Heritage Point': '购买土地（20土地花费1遗产点',
    'Buy forest (20 forest for 1 Heritage Point': '购买森林（20森林花费1遗产点',
    'Brushwood sell offer': '灌木出售报价',
    'Brushwood buy offer': '灌木购买报价',
    'Berry sell offer': '浆果出售报价',
    'Berry buy offer': '浆果购买报价',
    'Clothes buy offer': '衣服购买报价',
    'Clothes sell offer': '衣服出售报价',
    'Flour sell offer': '面粉出售报价',
    'Stone pickaxe sell offer': '石镐出售报价',
    'No enough Heritage Points!': '没有足够的遗产点数！',
    'Nature effects': '自然效果',
    'RESET ALL SETTINGS': '重置全部设置',
    'reset to default': '重置为默认',
    'Game options': '游戏选项',
    'resume game': '继续游戏',
    'Would it be useful to grind things up?': '研磨起来会有用吗？',
    'Stone shovel not researched!': '石铲没研究过！',
    'Weather not researched!"': '天气未研究！',
    'Are you sure you want to unlock researching Bow?': '你确定要解锁研究弓吗？',
    'food priority': '食物优先级',
    'page': '页',
    'Egg': '鸡蛋',
    'Are you sure you want to cancel crafting Cut stone?': '你确定要取消制作石材吗?',
    'Chicken pasture': '养鸡场',
    'constructing Manufacture': '结构制造',
    'constructing Quarry': '建造采石场',
    'constructing Tannery': '建造制革厂',
    'Cow pasture': '奶牛牧场',
    'crafting Cheese': '制作奶酪',
    'crafting Herbal medicine': '制作草药',
    'crafting Leather': '制作皮革',
    'crafting Stone pickaxe': '制作石镐',
    'crafting warehouse': '建造仓库',
    'cutting  cut stone': '切割石材',
    'deconstructing Hut': '建造小屋',
    'Do you still want to demolish this building?': '你还想拆掉这栋建筑吗?',
    'Faithful research': '忠实研究',
    'Herbal Medicine': '草药',
    'Horse pasture': '马匹牧场',
    'Manufacture specialises in crafting one recipe and…ion but it produces slightly faster than workshop': '制造商专门制作一个配方和...离子，但它比车间产生稍快',
    'People that won\'t find new home will leave the village': '那些找不到新家的人将离开这个村庄',
    'Pig pasture': '养猪场',
    'transporting plank': '运送木板',
    'upgrading Loggers hut': '升级伐木小屋',
    'We live to improve our knowledge. Gain 100 research points spent only on current research': '我们生活，提高我们的知识。 获得100个研究点仅用于当前的研究',
    'You don\'t have enough housing space to move this building occupants.': '您没有足够的住房空间来移动这栋建筑物的居住者。',
    'Are you sure you want to demolish Quarry?': '你确定要拆除采石场吗?',
    'Are you sure you want to unlock researching Trade routes?': '您确定要解锁研究贸易路线吗？',
    'Are you sure you want to unlock researching Wooden defences?': '你确定要解锁研究木制防御吗？',
    'constructing Barracks': '建造军营',
    'Stone shovel buy offer': '石铲购买报价',
    'constructing Hunter lodge': '建造猎人小屋',
    'Stone spear buy offer': '石矛购买报价',
    'tame animals': '你的动物',
    'transporting cut stone': '运送石材',
    'Wooden tower invented': '木塔已发明',
    'constructing Training square': '建造训练广场',
    'Wooden defences researched': '木制防御研究',
    'Master prospecting researched': '精通勘探研究',
    'Copper sell offer': '铜出售报价',
    'crafting Stone axe': '制作石斧',
    'crafting Stone shovel': '制作石铲',
    'Stockade invented': '栅栏发明',
    'Stone shovel sell offer': '石铲出售报价',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //更新日志
    'Bug fixes': '修复bug',
    'Fixed building Smithy required to research tech allowing to build it': '修复建筑铁匠铺需要研究技术，允许建立它',
    'New features': '新功能',
    'Doubled iron deposit find chance': '找到铁矿的机会翻倍',
    'Most probably fixed overscrolling from game to kongregate window': '最大可能修复了从游戏到kongregate窗口的滚动',
    'use metric units': '使用公制单位',
    'Ore deposits found limited at 50 each': '发现的矿床数量限制在50个',
    'Slightly increased happiness reduction from half food rations': '幸福指数从食物配给的一半略微下降',
    'Fixed limited buildings allowed to build over the limit': '修复有限制的建筑物允许建设超过限制',
    'Fixed missions finishing without calculating outcome': '修复任务结束没有计算结果',
    'Troops multiplier now shows multiplied required resources in tooltip. If you cannot afford - troop turns grey': '现在，部队乘数显示工具提示中所需的多个资源。 如果你负担不起 - 部队变灰了',
    'Added buttons to hire/fire workers in all currently viewed buildings': '在所有当前查看的建筑物中添加了雇佣/解雇工人的按钮',
    'Added option to show only current view tutorial': '添加了仅显示当前视图教程的选项',
    'Added Stonehenge effect for manufacture': '为制造增加了巨石阵效应',
    'Added troops list to mission in progress': '新增部队列出进行中的任务',
    'all off': '全部关闭',
    'all on': '全部开启',
    'building base power': '建设基础力量',
    'Changed some missions times': '改变了一些任务时间',
    'Changed wonders to reapply missing effects on soft reset or abdication': '改变奇迹，重新应用软重置或退位的缺失效果',
    'Choose recipe': '选择配方',
    'Decreased chicken and pigs breeding speed': '减少鸡和猪的繁殖速度',
    'Fixed Forester not returning land when demolished': '修复了林务员拆迁时没有返回土地的问题',
    'Fixed some wonders add effects after each reset': '修复了一些奇迹在每次重置后添加效果',
    'Forest management improved and moved into management tab': '森林管理得到改善，并进入管理标签',
    'Forestry research now requires management to be researched': '林业研究现在需要对管理进行研究',
    'Increased expeditions cost': '增加了探险费用',
    'Removed autofill \'1\' for crafting amount input': '删除自动填充"1"以进行制作量输入',
    'Information': '信息',
    'Performance': '性能',
    'Added button to show finished research projects': '添加按钮以显示已完成的研究项目',
    'Added Manufacture building for specialised crafting': '增加了专业制作的制造建筑',
    'Added more production details to buildings in build window': '在建筑窗口中向建筑物添加了更多生产细节',
    'Added research tab warning when no workshop is set to research': '在没有研究的工作台时增加研究选项卡警告',
    'Added special warning for demolishing housing building when there is no enough free space to move all occupants to': '当没有足够的空闲空间移动所有乘客时，增加了拆除房屋建筑的特别警告',
    'Added Specialised production research to unlock manufacture': '增加专业生产研究以解锁制造',
    'Added tooltips to resources in resource tab.': '在资源选项卡中添加了资源的工具提示。',
    'Arrange doesn\'t require to be researched anymore': '队列不再需要研究',
    'Changed expedition to take longer and cost more but give more land and kill less troops': '改变远征需要更长的时间和更多的成本，但增加土地，减少部队',
    'Changed work management option description (management tab) and added description message after researching Human Resources': '在研究人力资源后，更改了工作管理选项说明（管理选项卡）并添加了说明消息',
    'Changes for Royal Points granting events': '更改皇家点数授予事件',
    'Changes regarding workshop logic that might fix locking issue': '关于可能修复锁定问题的工作台逻辑的更改',
    'Church will now unlock Religion tab when built': '当建造教堂时现在将解锁宗教选项卡',
    'Consumable resources display nutrition': '可食用的资源显示营养',
    'Decreased recruitment times for all troops': '减少所有部队的招募时间',
    'Extended some buildings descriptions': '扩展了一些建筑物描述',
    'Fixed and improved building power modifier display to include permanent effects and correctly use weather multiplier': '修复和改进建筑力量修改器显示，包括永久效果和正确使用天气加成',
    'Fixed bug with New King buff lasting 0 days after reset or abdication': '修正了重置或退位后持续0天的新国王buff的bug',
    'Fixed metallurgy to add bronze recipe': '修复冶金添加青铜配方',
    'Fixed orchard harvest calculation when in autumn': '修复果园收成计算时，在秋季',
    'Increased fur production from hunters': '增加了猎人的毛皮产量',
    'Fixed wooden tower starting with decreased health': '修复木塔开始与下降的健康',
    'Fixed pastures limits updating to resources tab': '修复牧场限制更新到资源选项卡',
    'Fixed huts and houses ignoring fuel items reserved amounts': '修复棚屋和房屋忽略燃料项目预留金额',
    'Fixed manufacture producing even when there are no required resources': '修复即使没有所需资源，也可以生产',
    'Fixed orchard resources not available in resources and market before discovered via harvest': '修复果园资源在通过收获发现之前在资源和市场中不可用',
    'Fixed pastures not producing when there is mre than 1000 animals': '修复动物数量超过1000只时，动物就不能生产',
    'Fixed some imperfections on the background image': '修正了一些不完美的背景图像',
    'Added crafting cheese from milk (might require new run': '添加牛奶制作奶酪(可能需要重新运行',
    'Added new army troop': '增加了新的陆军部队',
    'Added new housing building': '增加了新的居住建筑',
    'Added nutrition usage to header nutrition tooltip': '为头部营养工具提示添加营养用量',
    'Added tooltip to market offers to show more information regarding the offer': '向市场报价添加了工具提示，以显示有关优惠的更多信息',
    'Animals now require food for the whole year ( less food required during spring, summer and autumn than in winter ': '动物现在成为全年必需食物（春季，夏季和秋季需要的食物少于冬季',
    //1.0.3
    'We pray for all live to thrive. 10% buff to natural sources for 5 years': '我们祈祷所有人都能活得更好。10%的自然资源增益5年',
    'We shall win any enemy with our faith. All troops buffed 20% for one year': '我们将用我们的信仰赢得任何敌人。 所有军队一年都增加了20％',
    'Added Heritage system that awards points based on population size on reset': '添加了遗产系统，根据重置时的人口规模奖励积分',
    'Added new health resources (no use yet': '添加了新的健康资源（尚未使用）',
    'Added possibility to add second row to header through management menu': '添加了通过管理菜单向标题添加第二行的可能性',
    'Apples growth time reduced by': '苹果的生长时间缩短了',
    'Big performance improvement': '大的性能提升',
    'Buildings names and effect font size will be automatically recalculated on change': '建筑物名称和效果字体大小将在更改时自动重新计算',
    'Changed arrange drag and drop to click and click': '更改了排列拖放以单击并单击',
    'Church will employ worker when finished building': '完成建筑后，教会将聘用工人',
    'Farm can now be upgraded to level': '农场现在可以升级到等级',
    'Fixed wonder construction not benefiting from construction effects': '修复奇迹建筑不受益于施工效果',
    'Greatly reduced alcohol consumption rate': '大大降低了酒精消费率',
    'Invasions will now have a recharge period when invasion threat will not grow': '当入侵威胁不再增长时，入侵将有一个恢复时间',
    'Invasions will now only happen when village reach certain size': '入侵只会发生在村庄达到一定规模的时候',
    'It\'s now possible to switch reserved value to be interpreted as reserve % of total limit': '现在可以将保留值转换为总限额的保留百分比',
    'New performance option in settings (give current default performance a try before changing options': '设置中的新性能选项（在更改选项之前尝试提供当前默认性能）',
    'Nutrition value will show in the header from the start': '营养价值将从头开始显示在标题中',
    'Performance options': '性能选项',
    'Researching windmill will now make fabric visible and tradeable': '研究风车将使织物可见并可交易',
    'Shrine and Church now have diminishing return from population size': '神殿和教堂的人口规模收益正在减少',
    'Total food nutrition': '总食物营养',
    'Upgrade arrow will now have green outline': '升级箭头现在会有绿色的轮廓',
    'Workers and population can now be added to header': '工人和人口现在可以添加到顶部',
    'Added a window for nature effects in effects management': '在效果管理中添加了自然效果窗口',
    'Added herbs to gatherer building description': '添加草药收集建筑描述',
    'Added new buildings filter for all/working/idle buildings': '为所有/工作/闲置建筑添加了新的建筑物过滤器',
    'Added new royal perk': '增加了新的皇家特权',
    'Added warning about low heating resources on start of autumn': '在秋季开始时增加了关于低供暖资源的警告',
    'Army troops will now require soldiers pay every 30 days.': '陆军现在要求每30天付一次钱给士兵。',
    'Decreased animals reproduction rate': '降低动物繁殖率',
    'Farm upgrade increases farm power': '农场升级增加了农场动力',
    'Fixed iron recipe not added after researching': '修复研究后没有添加铁配方',
    'If there is no enough coins to pay soldier has 25% chance to desert': '如果没有足够的硬币支付，士兵有25％的机会离开',
    'Increased high (90-100) happiness effect from 35% to': '增加高（90-100）幸福效应从35％至',
    'Increased workshops building size': '增加了工作台建筑面积',
    'Prioritized resources have higher chance to appear on market': '优先资源有更高的机会出现在市场上',
    'Renamed \'Leather\' research to \'Tannery\' and removed it from tailor prerequisites': '将“皮革”研究重新命名为“制革厂”并将其从裁缝先决条件中删除',
    'Vegetable and meat soups now require herbs': '蔬菜和肉类汤现在需要草药',
    'Added \'Herbalism\' research that allows to plant herbs at fields': '增加了“草药学”研究，允许在田间种植草药',
    'Added options to change positive and negative colours to user defined': '添加了将正负颜色更改为用户定义的选项',
    'Added pause/resume button in the footer': '在页脚中添加了暂停/恢复按钮',
    'Display options': '显示选项',
    'Fixed field harvest display and yield calculation': '修复田间收获展示和产量计算',
    'Fixed game freeze when coins were reserved': '修正了保留硬币时游戏冻结的问题',
    'Fixed House building awarded with King of the People perk. It now starts with 3 occupants': '修复房屋建筑获得了人民之王的奖励。 它现在以3名居住者开始',
    'Font colour for negative effects': '负面效果的字体颜色',
    'Font colour for positive effects': '正面效果的字体颜色',
    'Initial housing buildings start equipped with clothes': '最初的住房建筑开始配备衣服',
    'Manufacture no longer stops production during storm': '制造过程中不再停止生产',
    'Mathematics research will now also buff deconstructions': '数学研究现在也将进行缓解解构',
    'Mint building size increased, power decreased, output coins increased to be worth more than input resources': '薄荷建筑面积增加，功率下降，输出硬币增加值比输入资源更多',
    'Added food priority to management': '增加了食品优先管理',
    'Added settings option that allows to paginate buildings in regions.': '添加了设置选项，允许对区域中的建筑物进行分页。',
    'Display buildings in pages instead of all at once': '以页面显示建筑物而不是一次显示所有建筑物',
    'Fixed king of the people House building having too much population from start (6 instead of': '修复人民之王从一开始就拥有太多人口的住宅建筑（6而不是',
    'Fixed pit mine mining only 199 resources': '修复矿坑开采仅有199资源',
    'Fixed selling animals removing more than it should': '修复出售动物的数量超过了应有的数量',
    'Number of buildings on one page': '一页上的建筑数量',
    'Number of buildings per page can be also defined in settings': '每页的建筑数量也可以在设置中定义',
    'Pit mine base power reduced': '矿坑基础功率降低',
    'Workshops now show what resource they are waiting to deposit': '工作台现在显示了他们等待存放的资源',
    'Workshops won\'t start crafting if there is no space in warehouse or if warehouse will be filled to full by other workshops': '如果仓库里没有空间或者仓库被其他工作室填满，工作室将不会开始制作',
    //1.0.17
    'Added display of what golden items have been found during current run': '添加了当前运行期间找到的黄金项目的显示',
    'Alcohol unlocks beer and wine resources': '酒精解锁啤酒和葡萄酒资源',
    'Changed \'Royal prophecy\' 3rd perk to grant \'Bow\' and \'Hunting\' research instead of \'Mortar\'': '将“皇家预言”第三点奖励改为“弓箭”和“狩猎”研究，而不是“砂浆”',
    'Farms will now work on pastures during rain': '下雨时，农场将在牧场上耕作',
    'Fixed army payday countdown stuck and invasions being tied to this countdown': '修复军队发薪日倒计时卡住和入侵与这个倒计时有关',
    'Fixed day being 11 ticks instead of': '修复了一天是11个刻度而不是',
    'Fixed golden items not resetting correctly': '修复了未正确重置的黄金项目',
    'Fixed mountains tab deposits causing scroll bar to go below the screen': '修复了山脉标签存款导致滚动条进入屏幕下方',
    'Limited tavern to 1 (having more might be bad if they lack alcohol as negative/positive effects would be applied multiple times': '限制酒馆数量为1(如果他们缺少酒精，拥有更多的酒馆可能是不好的，因为消极/积极的影响将被应用多次',
    'Longhouse require hay instead of fabric (for roof), House require brushwood (also for roof': '长屋需要干草而不是织物(用于屋顶)，房子需要灌木(也用于屋顶)',
    'Pastures details now show how much meat current animals will yield': '牧场的细节现在显示了当前动物的肉产量',
    'Probably fixed tavern bug': '也许修正了酒馆的bug',
    'produced by': '生产通过',
    'Resources tooltips will now show who produced that item in the last 30 days': '工具提示不应该再出现在屏幕下面',
    'Tooltips should no longer go under the screen': '',
    'Windmill power and flour amount doubled, flour recipe cost reduced': '风车功率和面粉量翻了一番，面粉配方成本降低',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '°C': '°C',
    'v1.': 'v1.',
    '打开手机QQ': '打开手机QQ',
    '点击加群': '点击加群',
    '更多同类游戏': '更多同类游戏',
    '旧版': '旧版',
    '论坛': '论坛',
    '扫码加群': '扫码加群',
    '一起讨论吧': '一起讨论吧',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    '': '',
    '': '',

}

//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换
var cnRegReplace = new Map([
	[/^requires (\d+) more research points$/, '需要$1个研究点'],
	[/^(\d+) Royal points$/, '$1 皇家点数'],
	[/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
	[/^Usages: (\d+)\/$/, '用途：$1\/'],
	[/^workers: (\d+)\/$/, '工人：$1\/'],
	[/^Missing (\d+) Hay!$/, '缺少$1干草！'],
	[/^Missing (\d+) Food!$/, '缺少$1食物！'],
	[/^Missing (\d+) Fuel!$/, '缺少$1燃料！'],
	[/^Missing (\d+) Bow!$/, '缺少$1弓箭！'],
	[/^Missing (\d+) Stone!$/, '缺少$1石头！'],
	[/^Missing (\d+) Plank!$/, '缺少$1木板！'],
	[/^Missing (\d+) Herbs!$/, '缺少$1草药！'],
	[/^Missing (\d+) Coins!$/, '缺少$1硬币！'],
	[/^Missing (\d+) Berry!$/, '缺少$1浆果！'],
	[/^Missing (\d+) Brushwood!$/, '缺少$1灌木！'],
	[/^Missing (\d+) Cotton!$/, '缺少$1棉花！'],
	[/^Missing (\d+) Horse!$/, '缺少$1马匹！'],
	[/^Missing (\d+) Light armor!$/, '缺少$1轻甲！'],
	[/^Missing (\d+) Sword!$/, '缺少$1剑！'],
	[/^Missing (\d+) Tin!$/, '缺少$1锡！'],
	[/^Missing (\d+) Log!$/, '缺少$1木头！'],
	[/^Missing (\d+) Stone spear!$/, '缺少$1石矛！'],
	[/^Missing (\d+) Fur!$/, '缺少$1毛皮！'],
	[/^Missing (\d+) Stone shovel$/, '缺少$1石铲！'],
	[/^Missing (\d+) Stone axe!$/, '缺少$1石斧！'],
	[/^Missing (\d+) Stone shovel!$/, '缺少$1石铲！'],
	[/^Missing (\d+) Fabric!$/, '缺少$1织品！'],
	[/^Missing (\d+) Stone hammer!$/, '缺少$1石锤！'],
	[/^Missing (\d+) Copper ore!$/, '缺少$1铜矿石！'],
	[/^Missing (\d+) Stone pickaxe!$/, '缺少$1石镐！'],
	[/^Missing (\d+) Cut stone!$/, '缺少$1石材！'],
    [/^day: (\d+) year: (\d+) spring\n$/, '日: $1 年: $2 春天\n'],
    [/^day: (\d+) year: (\d+) summer\n$/, '日: $1 年: $2 夏天\n'],
    [/^day: (\d+) year: (\d+) autumn\n$/, '日: $1 年: $2 秋天\n'],
    [/^day: (\d+) year: (\d+) winter\n$/, '日: $1 年: $2 冬天\n'],
	[/^Incoming attack in (\d+) days!$/, '$1天内将受到攻击!'],
	[/^ (\d+) Brushwood$/, ' $1 灌木'],
    [/^ (\d+) Plank$/, ' $1 木板'],
    [/^ (\d+) Wheat$/, ' $1 小麦'],
    [/^ (\d+) Log$/, ' $1 木头'],
    [/^ (\d+) Cotton$/, ' $1 棉花'],
    [/^ (\d+) Hay$/, ' $1 干草'],
    [/^ (\d+) Stone$/, ' $1 石头'],
    [/^ (\d+) Berry$/, ' $1 浆果'],
    [/^ (\d+) Copper$/, ' $1 铜'],
    [/^(\d+) x Archer$/, ' $1 x 弓箭手'],
    [/^(\d+) x Militia$/, ' $1 x 民兵'],
    [/^(\d+) x Spearman$/, ' $1 x 枪兵'],
    [/^(\d+) x Light Cavalry$/, ' $1 x 轻骑兵'],
    [/^(\d+) x Swordsman$/, ' $1 x 剑士'],
    [/^(\d+) days$/, ' $1 天'],
    [/^(\d+) \/ soldier$/, '$1 \/ 士兵'],
	[/^duration: (\d+) days$/, '持续时间：$1 天'],
	[/^storage: (\d+)\/$/, '存储：$1\/'],
	[/^durability: (\d+)\/$/, '耐久：$1\/'],
    [/^occupants: (\d+)\/$/, '居住者: $1\/'],
	[/^Tutorial (\d+)\/$/, '教程 $1\/'],
	[/^ (\d+) in (\d+) days$/, ' $1 在 $2 天内'],
    [/^Your abdication granted you (\d+) royal points$/, '你的退位给了你 $1 皇家点数'],
	[/^\(limit: (\d+) building$/, '(限制: $1 建筑'],
    [/^There are less than (\d+) trees in the forest!$/, '森林里的树剩余不到$1棵！'],
    [/^(\d+)\/(\d+)\) would you like to$/, '$1\/$2\) 你是否想要'],
    [/^You will be awarded (\d+) Heritage Points$/, '您将获得 $1 遗产点'],
//	[/^Research points: (\d+)\/$/, '研究点: $1\/'],

]);

//2.采集新词
//20190320@JAR

var cnItem = function () {

    //传参是否非空字串
    if (!arguments[0]) return;

    //检验传参是否对象
    let text = arguments[0],
        s = '';
    if (typeof (text) != "string")
        return text;
    else
        s = arguments[0].charCodeAt();

    //检验传参是否英文
    // if (
    //     s < 65 || (s > 90 && s < 97) || (s > 122)
    //
    // ) return text;

    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix = cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix];
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0];
            text = text.substr(0, text.length - text_reg_exclude_postfix.length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return arguments[0];
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (
            text == i || text == cnItems[i] &&
            cnItems[i] != ''
        )
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : arguments[0]
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return arguments[0];
    }

    if (cnItems._OTHER_.length < 500) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function (a, b) {
                return a.localeCompare(b)
            }
        );
    }

    /*
        //开启生词打印
        //console.log(
            '有需要汉化的英文：', text
        );
    */

    //返回生词字串
    return arguments[0];
};

transTaskMgr = {
    tasks: [],
    addTask: function (node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function () {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "TEXTAREA" && subnode.innerHTML && subnode.innerText) {
                if (subnode.innerHTML === subnode.innerText) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function () {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function (e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.innerHTML && mutation.target.innerText && mutation.target.innerHTML === mutation.target.innerText) {
                mutation.target.innerText = cnItem(mutation.target.innerText);
            } else if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "TEXTAREA" && node.innerHTML && node.innerText) {
                        if (node.innerHTML === node.innerText) {
                            node.innerText = cnItem(node.innerText);
                        } else {
                            TransSubTextNode(node);
                            transTaskMgr.doTask();
                        }
                    }
                }
            }
        }
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
}();
